# github-app-credentials.yaml can be created using the following command:
# npx @backstage/cli create-github-app <github-org-name>
# and renaming the file to github-app-credentials.yaml or changing the include path in app-config.local.yaml

appId: 
webhookUrl: 
clientId: 
clientSecret: 
webhookSecret: 
privateKey: 
  